import { NextResponse } from "next/server";
import { getSession } from "@/lib/session";
import { prisma } from "@/lib/prisma";

function sanitizeAnnouncementHtml(input: string) {
  let html = input;

  // Remove dangerous elements and everything inside them.
  html = html.replace(
    /<(script|style|iframe|object|embed|svg|math)\b[^>]*>[\s\S]*?<\/\1\s*>/gi,
    ""
  );

  // Remove standalone dangerous elements.
  html = html.replace(
    /<(script|style|iframe|object|embed|svg|math)\b[^>]*\/?>/gi,
    ""
  );

  // Remove HTML comments.
  html = html.replace(/<!--[\s\S]*?-->/g, "");

  const allowedTags = new Set([
    "b",
    "strong",
    "i",
    "em",
    "u",
    "div",
    "p",
    "br",
    "ul",
    "ol",
    "li",
    "a",
  ]);

  html = html.replace(
    /<\/?([a-zA-Z0-9]+)(?:\s[^<>]*?)?>/g,
    (fullTag, rawTagName: string) => {
      const tag = rawTagName.toLowerCase();
      const closing = /^<\//.test(fullTag);

      if (!allowedTags.has(tag)) {
        return "";
      }

      if (closing) {
        return `</${tag}>`;
      }

      if (tag === "br") {
        return "<br>";
      }

      if (tag === "a") {
        const hrefMatch = fullTag.match(
          /\bhref\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s>]+))/i
        );

        const href = (hrefMatch?.[1] ?? hrefMatch?.[2] ?? hrefMatch?.[3] ?? "").trim();

        if (!/^https?:\/\//i.test(href)) {
          return "";
        }

        const escapedHref = href
          .replace(/&/g, "&amp;")
          .replace(/"/g, "&quot;")
          .replace(/</g, "&lt;")
          .replace(/>/g, "&gt;");

        return `<a href="${escapedHref}" target="_blank" rel="noopener noreferrer">`;
      }

      // Preserve ONLY center alignment from the editor.
      if (tag === "div" || tag === "p") {
        const styleMatch = fullTag.match(
          /\bstyle\s*=\s*(?:"([^"]*)"|'([^']*)')/i
        );

        const style = (styleMatch?.[1] ?? styleMatch?.[2] ?? "").toLowerCase();

        if (/text-align\s*:\s*center/.test(style)) {
          return `<${tag} style="text-align: center;">`;
        }
      }

      // Preserve list presentation generated by our editor.
      if (tag === "ul") {
        return '<ul style="list-style-type: disc; padding-left: 1.5rem; margin: 0.5rem 0;">';
      }

      if (tag === "ol") {
        return '<ol style="list-style-type: decimal; padding-left: 1.5rem; margin: 0.5rem 0;">';
      }

      return `<${tag}>`;
    }
  );

  // Remove any event-handler attributes that may remain in malformed input.
  html = html.replace(/\son[a-z]+\s*=\s*(?:"[^"]*"|'[^']*'|[^\s>]+)/gi, "");

  return html.trim();
}

async function getAdminUser() {
  const session = await getSession();
  const userId =
    typeof session?.userId === "string" ? session.userId : null;

  if (!userId) return null;

  return prisma.user.findFirst({
    where: {
      id: userId,
      role: "ADMIN",
      isActive: true,
    },
    select: {
      id: true,
      email: true,
    },
  });
}

export async function GET() {
  try {
    const admin = await getAdminUser();

    if (!admin) {
      return NextResponse.json(
        { error: "Unauthorized" },
        { status: 403 }
      );
    }

    const announcements = await prisma.announcement.findMany({
      orderBy: {
        createdAt: "desc",
      },
      take: 1,
    });

    return NextResponse.json({ announcements });
  } catch (error) {
    console.error("Unable to load announcements:", error);

    return NextResponse.json(
      { error: "Unable to load announcements." },
      { status: 500 }
    );
  }
}

export async function POST(request: Request) {
  try {
    const admin = await getAdminUser();

    if (!admin) {
      return NextResponse.json(
        { error: "Unauthorized" },
        { status: 403 }
      );
    }

    const body = await request.json();

    const title =
      typeof body.title === "string" ? body.title.trim() : "";

    const rawMessage =
      typeof body.message === "string" ? body.message.trim() : "";

    const message = sanitizeAnnouncementHtml(rawMessage);

    const buttonText =
      typeof body.buttonText === "string" && body.buttonText.trim()
        ? body.buttonText.trim()
        : null;

    const buttonUrl =
      typeof body.buttonUrl === "string" && body.buttonUrl.trim()
        ? body.buttonUrl.trim()
        : null;

    if (!title || !message) {
      return NextResponse.json(
        { error: "Headline and message are required." },
        { status: 400 }
      );
    }

    if (title.length > 120 || message.length > 2000) {
      return NextResponse.json(
        { error: "Announcement is too long." },
        { status: 400 }
      );
    }

    if (buttonText && buttonText.length > 40) {
      return NextResponse.json(
        { error: "Button text is too long." },
        { status: 400 }
      );
    }

    if (buttonUrl) {
      try {
        const url = new URL(buttonUrl);

        if (url.protocol !== "https:" && url.protocol !== "http:") {
          throw new Error("Invalid protocol");
        }
      } catch {
        return NextResponse.json(
          { error: "Please enter a valid button link." },
          { status: 400 }
        );
      }
    }

    const announcement = await prisma.announcement.create({
      data: {
        title,
        message,
        buttonText,
        buttonUrl,
        isActive: true,
      },
    });

    // Only the newest announcement is retained.
    // Related dismissal records are removed by the cascade relation.
    await prisma.announcement.deleteMany({
      where: {
        id: {
          not: announcement.id,
        },
      },
    });

    return NextResponse.json(
      { announcement },
      { status: 201 }
    );
  } catch (error) {
    console.error("Unable to publish announcement:", error);

    return NextResponse.json(
      { error: "Unable to publish announcement." },
      { status: 500 }
    );
  }
}
